name: Python Django CI
on:
  push:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    name: Python Django 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Build Docker Image
        run: docker build -t hello-world-django:latest .